# .sqa/config.yml - jenkins-pipeline-library configuration file
sqa_criteria:
  qc_style:
    repos:
      ai4life:
        container: testing
        commands:
        - flake8 --statistics --tee --output-file=./flake8.log --format=pylint ai4life api tests

  qc_coverage:
    repos:
      ai4life:
        container: testing
        commands:
        - pytest --cov=api --cov=ai4life --cov-report=html:./htmlcov --cov-report=term-missing tests

  qc_security:
    repos:
      ai4life:
        container: testing
        commands:
        - mkdir -p /srv/app/bandit
        - bandit -r ai4life api -x tests -o ./bandit/index.html

environment:
  GIT_COMMITTER_NAME: "Fahimeh Alibabaei "
  GIT_COMMITTER_EMAIL: "khadijeh.alibabaei@kit.edu"
  JPL_DOCKERFORCEBUILD: "True"
  LANG: C.UTF-8

timeout: 900
