version: "3.6"

services:
  testing:
    container_name: "${BUILD_TAG}"
    hostname: "${BUILD_TAG}"
    working_dir: /srv
    build:
      context: ./.sqa
      args:
        branch: ${GIT_BRANCH}
    volumes:
      - type: bind
        source: ./
        target: /srv/app