version: "3.6"

services:
  testing:
    image: "ai4oshub/ai4os-ai4life-loader:cicd"
    container_name: "${BUILD_TAG}"
    hostname: "${BUILD_TAG}"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
