name: Filter v0_5 Models Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC

jobs:
  filter_models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bioimageio.core[onnx,pytorch]

    - name: Download collection.json
      run: |
        curl -o models/collection.json https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io/collection.json

    - name: Run Filter Script
      run: |
        python ai4life/filter_v0_5_models.py --input models/collection.json --output models/filtered_models.json
        

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update filtered_models.json"
        file_pattern: "models/filtered_models.json"